app/main/routes.py
import secrets
from app.models import Product, Payment, News, Agent, Project, Properties
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint, session
from app import db, mail
from app.forms import ContactForm, PaymentForm, SearchPropForm, SearchAgentForm, SearchProjForm
from app.models import User
from flask_login import current_user, login_required
from flask_mail import Message
from app.users.utils import save_picture

main = Blueprint('main', __name__)


@main.route('/', methods=['GET', 'POST'])
def index():
    product = Product.query.all()
    form = SearchPropForm()
    return render_template("index.html", product=product, form=form)


@main.route('/about', methods=['GET', 'POST'])
def about():
    return render_template("about.html")


@main.route('/projects', methods=['GET', 'POST'])
def projects():
    project = Project.query.all()
    return render_template("projects.html", project=project)


@main.route('/properties', methods=['GET', 'POST'])
def properties():
    property = Properties.query.all()
    return render_template("properties.html", property=property)


@main.route('/agents', methods=['GET', 'POST'])
def agents():
    agent = Agent.query.all()
    form = SearchAgentForm()
    return render_template("agents.html", agent=agent, form=form)



@main.route('/news', methods=['GET', 'POST'])
def news():
    news = News.query.all()
    return render_template("news.html", news=news)



@main.route('/gallery', methods=['GET', 'POST'])
# @login_required
def gallery():
    return render_template("gallery.html")


@main.route('/returnpolicy', methods=['GET', 'POST'])
def returnpolicy():
    return render_template("return.html")


@main.route('/terms', methods=['GET', 'POST'])
def terms():
    return render_template("terms.html")


@main.route('/privacy', methods=['GET', 'POST'])
def privacy():
    return render_template("privacy.html")



@main.route('/contact', methods=['GET', 'POST'])
def contact():
    user = User
    form = ContactForm()
    if form.validate_on_submit():
        msg = Message(f'New Message from {form.name.data}', sender=f'{user.email}',
                      recipients=['support@emax-solution.com'])
        msg.body = f"""
           Name :  {form.name.data}

           Email :  {form.contact_email.data}

           Phone Number :  {form.number.data}

           Message :  {form.message.data}
           """
        mail.send(msg)
        flash('your message have been sent', 'success')
        return redirect(url_for('main.index'))
    return render_template('contact.html', title='contact Form', form=form)


@main.route('/payment', methods=['GET', 'POST'])
@login_required
def payment():
    global image_file
    if 'shoppingcart' not in session or len(session['shoppingcart']) <= 0:
        return redirect(url_for('product.product'))
    form = PaymentForm()
    if form.validate_on_submit():
        if form.image.data:
            picture_file = save_picture(form.image.data)
            image = picture_file
        description = form.description.data
        author = current_user
        product = Payment(image=image, description=description, author=author)
        db.session.add(product)
        db.session.commit()
        flash(
            'Your Payment proof has been uploaded successfully, Admin will get back to you whenever your payment is approved!',
            'success')
        return redirect(url_for('main.thanks'))
    elif request.method == 'GET':
        image_file = url_for('static', filename='img/' + current_user.image_file)

    subtotal = 0
    grandtotal = 0
    for key, product in session['shoppingcart'].items():
        discount = 0
        discount = (discount / 100) * float(product['price'].replace(',', ''))

        subtotal += float(product['price'].replace(',', ''))
        subtotal -= discount

        grandtotal = "{:,.2f}".format(subtotal)

    return render_template('payments.html', grandtotal=grandtotal, product=product, form=form, image_file=image_file)


@main.route('/proof')
@login_required
def proof():
    payment = Payment.query.all()
    return render_template('admin/proof.html', payment=payment)


# @main.route("/delete_proof/<int:payment_id>/delete", methods=['GET', 'POST'])
# def delete_proof(payment_id):
#     product = Payment.query.get_or_404(payment_id)
#     if current_user.email != 'orjiobiajulum@yahoo.com':
#         abort(403)
#     db.session.delete(product)
#     db.session.commit()
#     flash("the product has been deleted successfully", 'success')
#     return redirect(url_for('admin.admin1'))
#     return render_template("admin/proof.html", product=product)


@main.route("/delete_new/<int:new_id>/delete", methods=['GET', 'POST'])
def delete_new(new_id):
    new = News.query.get_or_404(new_id)
    if current_user.email != 'orjiobiajulum@yahoo.com':
        abort(403)
    db.session.delete(new)
    db.session.commit()
    flash("the product has been deleted successfully", 'success')
    return redirect(url_for('admin.admin1'))
    return render_template("admin.html", new=new)


@main.route("/delete_post/<int:post_id>/delete", methods=['GET', 'POST'])
def delete_post(post_id):
    post = Agent.query.get_or_404(post_id)
    if current_user.email != 'orjiobiajulum@yahoo.com':
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash("the product has been deleted successfully", 'success')
    return redirect(url_for('admin.admin1'))
    return render_template("admin.html", post=post)

@main.route("/delete_prop/<int:prop_id>/delete", methods=['GET', 'POST'])
def delete_prop(prop_id):
    prop = Properties.query.get_or_404(prop_id)
    if current_user.email != 'orjiobiajulum@yahoo.com':
        abort(403)
    db.session.delete(prop)
    db.session.commit()
    flash("the product has been deleted successfully", 'success')
    return redirect(url_for('admin.admin1'))
    return render_template("admin.html", prop=prop)


@main.route("/delete_proj/<int:proj_id>/delete", methods=['GET', 'POST'])
def delete_proj(proj_id):
    proj = Project.query.get_or_404(proj_id)
    if current_user.email != 'orjiobiajulum@yahoo.com':
        abort(403)
    db.session.delete(proj)
    db.session.commit()
    flash("the product has been deleted successfully", 'success')
    return redirect(url_for('admin.admin1'))
    return render_template("admin.html", proj=proj)


@main.route('/thanks')
@login_required
def thanks():
    return render_template('thank.html')




# search button goes here

@main.context_processor
def layout():
	form = SearchPropForm()
	return dict(form=form)

 
@main.route('/searchprop', methods=["POST"])
def searchprop():
	form = SearchPropForm()
	prop = Properties.query

	if form.validate_on_submit():
		# Get data from submitted form
		post.searched = form.searched.data
		# Query the Database
		prop = prop.filter(Properties.name.like('%' + post.searched + '%'))
		prop = prop.order_by(Properties.location).all()

		return render_template("searchprop.html",
		 form=form,
		 searched = post.searched,
		 prop = prop)



@main.route('/posts/<int:id>')
def post(id):
	prop = Properties.query.get_or_404(id)
	return render_template('users.html', prop=prop)


@main.route('/searchproj', methods=["POST"])
def searchproj():
	form = SearchProjForm()
	proj = Project.query

	if form.validate_on_submit():
		# Get data from submitted form
		posts.searched = form.searched.data
		# Query the Database
		proj = proj.filter(Project.name.like('%' + posts.searched + '%'))
		proj = proj.order_by(Project.location).all()

		return render_template("searchproj.html",
		 form=form,
		 searched = posts.searched,
		 proj = proj)



@main.route('/posts/<int:id>')
def posts(id):
	proj = Project.query.get_or_404(id)
	return render_template('users.html', proj=proj)

app/order/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
# from app.models import Checkout
from flask_login import current_user, login_required

from app import db
order = Blueprint('order', __name__)


# @order.route('/orders', methods=['GET', 'POST'])
# @login_required
# def orders():
#     checkout = Checkout.query.all()
#     return render_template('admin/orders.html', checkout=checkout)


# @order.route("/delete_order/<int:order_id>/delete", methods=['GET', 'POST'])
# def delete_order(order_id):
#     order = Checkout.query.get_or_404(order_id)
#     if current_user.email != 'emeraldinteriorservices@gmail.com':
#         abort(403)
#     db.session.delete(order)
#     db.session.commit()
#     flash("the product has been deleted successfully", 'success')
#     return redirect(url_for('admin.home'))
#     return render_template("admin/home.html", order=order)

app/users/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint, session
from app import db, bcrypt
from app.models import User, Userreg, Agent
from flask_login import login_user, current_user, logout_user, login_required
from app.users.utils import save_picture, send_password_reset_email
from app.users.forms import LoginForm, RegistrationForm, UpdateAccountForm, ResetPasswordForm, RequestResetForm, UserForm, SearchAgentForm

users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, phone=form.phone.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'Welcome {form.username.data} Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template("register.html", title='Register', form=form)


@users.route('/register_option', methods=['GET', 'POST'])
def register_option():
    return render_template("register_option.html")


@users.route('/register_user', methods=['GET', 'POST'])
def register_user():
  
    form = UserForm()
    if form.validate_on_submit():
        
        username = form.username.data
        email = form.email.data
        password = form.password.data
       
        
        use = Userreg(email=email, password=password, username=username)
        db.session.add(use)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.index'))
    
    return render_template("register_user.html", form=form)



# search Agents button goes here 

@users.context_processor
def layout():
	form = SearchAgentForm()
	return dict(form=form)


 
@users.route('/searchagent', methods=["POST"])
def searchagent():
	form = SearchAgentForm()

	agent = Agent.query

	if form.validate_on_submit():
		# Get data from submitted form
		post.searched = form.searched.data
		# Query the Database
		agent = agent.filter(Agent.name.like('%' + post.searched + '%'))
		agent = agent.order_by(Agent.email).all()

		return render_template("searchagent.html",
		 form=form,
		 searched = post.searched,
		 agent = agent)



@users.route('/posts/<int:id>')
def post(id):
	user = Agent.query.get_or_404(id)
	return render_template('users.html', user=user)



@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            flash('Welcome to emax-solution.', 'success')
            return redirect(next_page) if next_page else redirect(url_for('main.index'))
        else:
            flash('registartion unsuccessful.please check your Email and password', 'danger')
    return render_template('login.html', form=form)


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='img/' + current_user.image_file)
    return render_template("account.html", image_file=image_file, form=form)


@users.route("/delete_user/<int:user_id>/delete", methods=['GET', 'POST'])
def delete_user(user_id):
    user = User.query.get_or_404(user_id)
    if current_user.id != 2:
        abort(403)
    db.session.delete(user)
    db.session.commit()
    flash("the user has been deleted successfully", 'success')
    return redirect(url_for('admin.home'))
    return render_template("users.html", user=user)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.index'))


@users.route('/reset_password', methods=['POST', 'GET'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            send_password_reset_email(user)
        flash('An email has been sent with instructions to reset your password', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route('/reset_password-<token>', methods=['POST', 'GET'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if not user:
        flash('Invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('your password has been updated!.', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

app/templates/admin.html
{% extends 'layouts.html' %}
{% block content %}

  <!-- Area Chart Example-->
  <div class="card mb-3">
        <div class="card-header">
          <i class="fas fa-chart-area"></i>
          Growth Of Users per Year</div>
        <div class="card-body">
          <canvas id="myAreaChart" width="100%" height="30"></canvas>
        </div>
        <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
      </div>
           
{% endblock content %}

app/templates/adminagent.html
{% extends 'layouts.html' %}

{% block content %}

   <div id="content-wrapper">

     <div class="container-fluid">

       <!-- Breadcrumbs-->
       <ol class="breadcrumb">
         <li class="breadcrumb-item">
           <a href="#">Dashboard</a>
         </li>
         <li class="breadcrumb-item active">Tables</li>
       </ol>

       <!-- Post DataTables Example -->
       <br><br>  <h2 style="text-align:center ;"> AGENTS TABLE</h2> 
       <div class="col-md-7 align-self-center">
        <a href="{{url_for('posts.agentpost')}}" class="btn waves-effect waves-light btn btn-info pull-right hidden-sm-down"> Upload Your Profile</a>
        <p>Click on the above button and upload your profile so users can be able to find you in agents page</p>
    </div><br>
       <div class="card mb-3">
         <div class="card-header">
           <i class="fas fa-table"></i>
           Data Table Example</div>
         <div class="card-body">
           <div class="table-responsive">
             <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
               <thead>
                 <tr>
                   <th>ID</th>
                   <th> Name</th>
                   <th>Image</th>
                   <th>Email</th>
                   <th>Phone</th>
                   
                   <th>Edit</th>
                   <th>Action</th>
                 </tr>
               </thead>
               <tbody>
                {% for post in agent %}
                 <tr>
                  <td> {{post.id}} </td>
                   <td>{{ post.name }}</td> 
                   <td><img  src="{{url_for('static', filename='img/' + post.image)}}" width="50" height="50"/></td>
                   <td>{{post.email}}</td>
                   <td>{{post.phone}}</td>
                   
                   <td><a class="btn-success btn" href=""> Edit </a></td>
                   <td>
                     <button type="button" class="btn btn-danger btn-sm m-2" data-toggle="modal" data-target="#deleteModal">Delete</button>
                   </td>
                 </tr>

                 <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModal" aria-hidden="true">
                      <div class="modal-dialog" role="document">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h5 class="modal-title" id="deleteModalLabel">Delete Post</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <form action="{{url_for('main.delete_post',post_id=post.id)}}" method="POST" style="display: inline-block">
                                <input class="btn-danger" type="submit" value="Delete">
                            </form>
                          </div>
                        </div>
                      </div>
                    </div>
                {% endfor %}

               </tbody>
             </table>
           </div>

         </div>
         <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
       </div>



     </div>
     </div>

     <!-- /.container-fluid -->
       {% endblock content %}

app/templates/adminnews.html
{% extends 'layouts.html' %}

{% block content %}

   <div id="content-wrapper">

     <div class="container-fluid">

       <!-- Breadcrumbs-->
       <ol class="breadcrumb">
         <li class="breadcrumb-item">
           <a href="#">Dashboard</a>
         </li>
         <li class="breadcrumb-item active">Tables</li>
       </ol>

       <!-- Post DataTables Example -->
       <br><br>  <h2 style="text-align:center ;"> NEWS TABLE</h2> 
       <div class="col-md-7 align-self-center">
        <a href="{{url_for('posts.newspost')}}" class="btn waves-effect waves-light btn btn-info pull-right hidden-sm-down"> Add News</a>
    </div><br>
       <div class="card mb-3">
         <div class="card-header">
           <i class="fas fa-table"></i>
           Data Table Example</div>
         <div class="card-body">
           <div class="table-responsive">
             <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
               <thead>
                 <tr>
                   <th>ID</th>
                   
                   <th>Image</th>
                   <th>Title</th>
                   <th>Description</th>
                   
                   <th>Edit</th>
                   <th>Action</th>
                 </tr>
               </thead>
               <tbody>
                {% for new in news %}
                 <tr>
                  <td> {{new.id}} </td>
                  <td><img  src="{{url_for('static', filename='img/' + new.image)}}" width="50" height="50"/></td>
                   <td>{{ new.title }}</td> 
                   
                   <td>{{new.description}}</td>
                    
                   <td><a class="btn-success btn" href=""> Edit </a></td>
                   <td>
                     <button type="button" class="btn btn-danger btn-sm m-2" data-toggle="modal" data-target="#deleteModal">Delete</button>
                   </td>
                 </tr>

                 <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModal" aria-hidden="true">
                      <div class="modal-dialog" role="document">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h5 class="modal-title" id="deleteModalLabel">Delete Post</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <form action="{{url_for('main.delete_new',new_id=new.id)}}" method="POST" style="display: inline-block">
                                <input class="btn-danger" type="submit" value="Delete">
                            </form>
                          </div>
                        </div>
                      </div>
                    </div>
                {% endfor %}

               </tbody>
             </table>
           </div>

         </div>
         <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
       </div>



     </div>
     </div>

     <!-- /.container-fluid -->
       {% endblock content %}

app/templates/adminproperties.html
{% extends 'layouts.html' %}

{% block content %}

   <div id="content-wrapper">

     <div class="container-fluid">

       <!-- Breadcrumbs-->
       <ol class="breadcrumb">
         <li class="breadcrumb-item">
           <a href="#">Dashboard</a>
         </li>
         <li class="breadcrumb-item active">Tables</li>
       </ol>

       <!-- Post DataTables Example -->
       <br><br>  <h2 style="text-align:center ;"> PROPERTY LIST </h2> 
       <div class="col-md-7 align-self-center">
        <a href="{{url_for('posts.propertiespost')}}" class="btn waves-effect waves-light btn btn-info pull-right hidden-sm-down"> Add New Property</a>
    </div><br>
       <div class="card mb-3">
         <div class="card-header">
           <i class="fas fa-table"></i>
           Data Table Example</div>
         <div class="card-body">
           <div class="table-responsive">
             <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
               <thead>
                 <tr>
                   <th>ID</th>
                   <th> Name</th>
                   <th>Image</th>
                   <th>Price</th>
                   <th>Square</th>
                   <th>Status</th>
                   <th>Price</th>
                   <th>No Of Bed</th>
                   <th>No Of floor</th>
                   <th>No Of Bat</th>
                   <th>Location</th>
                   <th>Edit</th>
                   <th>Action</th>
                 </tr>
               </thead>
               <tbody>
                {% for prop in property %}
                 <tr>
                  <td> {{prop.id}} </td>
                   <td>{{ prop.name }}</td> 
                   <td><img  src="{{url_for('static', filename='img/' + prop.image)}}" width="50" height="50"/></td>
                   <td>{{prop.price}}</td>
                   <td>{{prop.square}}</td>
                   <td>{{prop.status}}</td>
                   <td>{{prop.bathroom}}</td> 
                   <td>{{prop.bedroom}}</td> 
                   <td>{{prop.floors}}</td> 
                   <td>{{prop.location}}</td> 
                   <td><a class="btn-success btn" href=""> Edit </a></td>
                   <td>
                     <button type="button" class="btn btn-danger btn-sm m-2" data-toggle="modal" data-target="#deleteModal">Delete</button>
                   </td>
                 </tr>

                 <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModal" aria-hidden="true">
                      <div class="modal-dialog" role="document">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h5 class="modal-title" id="deleteModalLabel">Delete Post</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <form action="{{ url_for('main.delete_prop',prop_id=prop.id) }}" method="POST" style="display: inline-block">
                                <input class="btn-danger" type="submit" value="Delete">
                            </form>
                          </div>
                        </div>
                      </div>
                    </div>
                {% endfor %}

               </tbody>
             </table>
           </div>

         </div>
         <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
       </div>



     </div>
     </div>

     <!-- /.container-fluid -->
       {% endblock content %}

app/templates/register_option.html
{% extends "layout.html"%}

{% block content%}


<div id="app">
    <section class="main-homes">
    <div
        class="bgheadproject hidden-xs"
        style="background: url('static/storage/general/breadcrumb-background.jpg')"
    >
        <div class="description">
            <div class="container-fluid w90">
                <h2 class="text-center">I am signing up as...</h2>
                <h6 class="text-center">Click to continue</h6>
              
            </div>
        </div>
    </div>


    <div class="container-fluid w90 padtop30 col-lg-10">
        <div class="rowm10">
                            <div  class="container-fluid">
                    <div class="row rowm10 list-agency col-md-12">

                        

       
                                                    <div class="col-lg-4 ">
                                <div class="agents-grid">

    <div class="agents-grid-wrap">

        <div class="fr-grid-thumb">
                            <a  href="{{ url_for('users.register') }}">
                    <img src="../static/storage/accounts/agent.png"   class="img-fluid mx-auto" alt="Faye Sauer">
                </a>
                    </div>

        <div class="fr-grid-detail">
            <div class="fr-grid-detail-flex">
                <h5 class="fr-can-name">
                                            <a href="{{ url_for('users.register') }}">AGENT</a>
                                    </h5>
            </div>
                           
                    </div>

    </div>

    

    <div class="fr-grid-footer">
        <div class="fr-grid-footer-flex">
            <span class="fr-position"><i class="fa fa-user"></i>&nbsp;</span>
        </div>
                    <div class="fr-grid-footer-flex-right">
                <a href="{{ url_for('users.register') }}" class="prt-view" tabindex="0">Get Started</a>
            </div>
            </div>

</div>

                            </div>

                            <div class="col-lg-4 ">
                                <div class="agents-grid">

    <div class="agents-grid-wrap">

        <div class="fr-grid-thumb">
                            <a  href="{{ url_for('users.register') }}">
                    <img src="../static/storage/accounts/landlord.png"   class="img-fluid mx-auto" alt="Faye Sauer">
                </a>
                    </div>

        <div class="fr-grid-detail">
            <div class="fr-grid-detail-flex">
                <h5 class="fr-can-name">
                                            <a href="{{ url_for('users.register') }}">LANDLORD</a>
                                    </h5>
            </div>
                           
                    </div>

    </div>

    

    <div class="fr-grid-footer">
        <div class="fr-grid-footer-flex">
            <span class="fr-position"><i class="fa fa-user"></i>&nbsp;</span>
        </div>
                    <div class="fr-grid-footer-flex-right">
                <a href="{{ url_for('users.register') }}" class="prt-view" tabindex="0">Get Started</a>
            </div>
            </div>

</div>

                            </div>
                                                    <div class="col-lg-4 ">
                                <div class="agents-grid">

    <div class="agents-grid-wrap">

        <div class="fr-grid-thumb">
                            <a href="{{ url_for('users.register_user') }}">
                    <img src="../static/storage/accounts/user.png" class="img-fluid mx-auto" alt="Ismael Walter">
                </a>
                    </div>

        <div class="fr-grid-detail">
            <div class="fr-grid-detail-flex">
                <h5 class="fr-can-name">
                                            <a href="{{ url_for('users.register_user') }}">USER</a>
                                    </h5>
            </div>
                           
                    </div>

    </div>

   

    <div class="fr-grid-footer">
        <div class="fr-grid-footer-flex">
            <span class="fr-position"><i class="fa fa-users"></i>&nbsp;</span>
        </div>
                    <div class="fr-grid-footer-flex-right">
                <a href="{{ url_for('users.register_user') }}" class="prt-view" tabindex="0">Get Started</a>
            </div>
            </div>

</div>

                            </div>
                                                    
                        
                                            </div>
                </div>
                    </div>
    </div>
</section>
<br>
<br>

</div>


{% endblock content%}